### ISSUE TITLE
get_task() only retrieves single task instead of all matches

### ISSUE THREAD

**Issue by TheBaronHimself** [ralphbean/taskw#115]
I want to write a script that retrieves all tasks matching certain criteria (e.g. all tasks scheduled for a certain day). However, `get_task()` only seems to return the first matching task and ignores other matches. Is this by design? The name seems to imply so. Should I implement my own method to achieve what I want?

**Comment by coddingtonbear** [comment]
You might be looking for `filter_task(<filter dict>)` (https://github.com/ralphbean/taskw/blob/develop/taskw/warrior.py#L588)

**Comment by TheBaronHimself** [comment]
Ha, that works. Thanks. Wasn't reading too much beyond the README. I probably should have. 

<3
