### ISSUE TITLE
UUID parsing of created task fails with recur

### ISSUE THREAD

**Issue by matt-snider** [ralphbean/taskw#120]
There is a bug in the logic that parses UUIDs after a task is created. 

The issue occurs when adding a task with `recur` set, since the output is different:
```sh
$ task add "Take out garbage" rc.verbose:new-uuid  due:sow recur:weekly
Created task 4febf3b5-379a-41d4-b1b1-c0160f0b801c (recurrence template).
```
The code in question is [here](https://github.com/ralphbean/taskw/blob/32a87235f67a1e31dad1ef52873da9273f02b3ab/taskw/warrior.py#L688), and doesn't expect the bit with _recurrence template_. We end up parsing `uuid = 'template)'` and the command fails when getting the task:

```python
>>> try:
...    taskwarrior.task_add('Take out garbage', due='sow', recur='weekly')
... except TaskwarriorError as e:
...    print(b' '.join(e.command))
...    print(e.stderr)

b'task rc:~/.taskrc rc.json.array=TRUE rc.verbose=new-uuid rc.confirmation=no rc.dependency.confirmation=no export template)'

b'Configuration override rc.json.array:TRUE\nConfiguration override rc.verbose:new-uuid\nConfiguration override rc.confirmation:no\nConfiguration override rc.dependency.confirmation:no\nMismatched parentheses in expression'
```

**Comment by bergercookie** [comment]
This probably is already implemented since https://github.com/ralphbean/taskw/pull/121 is already merged.

**Comment by matt-snider** [comment]
Woops, yes I should have closed this a long time ago
