### ISSUE TITLE
taskw should circumvent around TW-1510

### ISSUE THREAD

**Issue by tbabej** [ralphbean/taskw#88]
utils.py, encode_task_experimental, line 128 should say something along the line of

            "%s:\"%s\"" % (k, v) if v != '' else "%s:" % k

**Comment by ralphbean** [comment]
According to the ``#taskwarrior`` backlog, we should look at this because of things discussed here:

- https://bug.tasktools.org/browse/TW-1510
- https://bug.tasktools.org/browse/TD-87
