### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by iElectric** [ralphbean/taskw#90]
Hey,

is there any possibility of a release, current release doesn't pass tests for taskwarrior 2.4.0:

http://hydra.nixos.org/build/19556750/nixlog/1/raw

**Comment by ralphbean** [comment]
Yes.  I was waiting on taskwarrior-2.4.1 since there are some problems with 2.4.0, but we can go ahead and cut a release.  Apologies for the delay.

**Comment by ralphbean** [comment]
Okay!  1.0.0 is up on PyPI now -> https://pypi.python.org/pypi/taskw

**Comment by iElectric** [comment]
:beers:
